dense:
  keep_dims: False
  type: tensorflow

lstm:
  keep_dims: True
  type: tensorflow

cnn:
  keep_dims: True
  type: tensorflow

decisiontree:
  keep_dims: False
  type: sklearn

lasso:
  keep_dims: False
  type: sklearn