aljarafe:
  seq_len:
    - 24
    - 72
    - step: 24
  pred_len:
    - 1
    - 8
    - 16
    - 24
  shift:
    - 24
  select_timesteps:
    - True

asomadilla:
  seq_len:
    - 24
    - 72
    - step: 24
  pred_len:
    - 1
    - 8
    - 16
    - 24
  shift:
    - 24
  select_timesteps:
    - True

bermejales:
  seq_len:
    - 24
    - 72
    - step: 24
  pred_len:
    - 1
    - 8
    - 16
    - 24
  shift:
    - 24
  select_timesteps:
    - True

rondadelvalle:
  seq_len:
    - 24
    - 72
    - step: 24
  pred_len:
    - 1
    - 8
    - 16
    - 24
  shift:
    - 24
  select_timesteps:
    - True

torneo:
  seq_len:
    - 24
    - 72
    - step: 24
  pred_len:
    - 1
    - 8
    - 16
    - 24
  shift:
    - 24
  select_timesteps:
    - True