dense:
  keep_dims: False
  layers:
    - 2
    - 3
  units:
    - 24
    - 72
  dropout: 0.2
  batch_size: 128
  lr: 0.001
  type: tensorflow

gradientboosting:
  max_depth:
    - 3
    - 5
  n_estimators:
    - 50
    - 100
  batch_size: 128
  type: sklearn

customboosting:
  max_depth:
    - 3
    - 5
  n_estimators:
    - 50
    - 100
  batch_size: 128
  type: sklearn